version: '2'
services:
  playlist:
    build: micrometafyplaylist
    ports:
      - 8081:8080
  query:
    build: micrometafyquery
    ports:
      - 8080:8080
  nginx:
    build: webapp
    ports:
      - 80:80